name: Deploy Terraform

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Repo
      run: ls -R

    - uses: actions/setup-node@v2
      with:
        node-version: 24.14.1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform/env/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform/env/dev
      
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform/env/dev

    - name: Debug Repo Structure
      run: |
        echo "Current directory:"
        pwd
        echo "Listing files:"
        ls -R